# Generated by Django 2.2.6 on 2019-12-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'permissions': (('read_category', 'Can read the category'), ('create_category', 'Can create the category'), ('update_category', 'can update the category'), ('remove_category', 'can remove the category')),
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('prodcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
            options={
                'permissions': (('read_product', 'Can read the product'), ('create_product', 'Can create the product'), ('update_product', 'can update the product'), ('remove_product', 'can remove the product')),
            },
        ),
    ]
