# Generated by Django 2.2.6 on 2019-12-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191204_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('read_category', 'Can read the category'), ('create_category', 'Can create the category'), ('update_category', 'can update the category'), ('remove_category', 'can remove the category'))},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('read_product', 'Can read the product'), ('create_product', 'Can create the product'), ('update_product', 'can update the product'), ('remove_product', 'can remove the product'))},
        ),
    ]
